name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    paths:
      '**.cpp'
    branches:
      'master'
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          mode: exactly
          count: 0
          labels: 'lable-exactly'
      
